name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            # Use Boards Manager to install the latest release of the platform to get the toolchain.
            - name: arduino:avr
            # Overwrite the Boards Manager installation with the development version of the platform.
            - source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
              name: rp2040:rp2040
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./Firmware
          libraries: |
            # The "blink" sketch being compiled in this demo doesn't use any libraries, so just use an empty list
            #- name: Adafruit_GFX
             - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
             - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
             - source-url: https://github.com/adafruit/Adafruit_INA219.git
             - source-url: https://github.com/adafruit/Adafruit_NeoPixel.git
          fqbn: "rp2040:rp2040:seeed_xiao_rp2040"


